apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: integrated-gateway
spec:
  type: NodePort
  ports:
    - port: 8010
      name: server
      targetPort: 8010
      nodePort: 30010
  selector:
    app: integrated-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrated-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrated-gateway
  template:
    metadata:
      labels:
        appName: integrated-gateway
        app: integrated-gateway
    spec:
      containers:
        - name: integrated-gateway
          image: "{{ .Values.image.repository }}integrated-gateway"
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8010
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
