apiVersion: v1
kind: Service
metadata:
  name: praise-consumer-service
  labels:
    app: integrated-praise-consumer
spec:
  type: ClusterIP
  ports:
    - port: 8014
      name: server
  selector:
    app: integrated-praise-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrated-praise-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrated-praise-consumer
  template:
    metadata:
      labels:
        appName: integrated-praise-consumer
        app: integrated-praise-consumer
    spec:
      containers:
        - name: integrated-praise-consumer
          image: "{{ .Values.image.repository }}integrated-praise-consumer"
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8014
