apiVersion: v1
kind: Service
metadata:
  name: praise-provider-service
  labels:
    app: integrated-praise-provider
spec:
  type: ClusterIP
  ports:
    - port: 8015
      name: server
  selector:
    app: integrated-praise-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrated-praise-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrated-praise-provider
  template:
    metadata:
      labels:
        appName: integrated-praise-provider
        app: integrated-praise-provider
    spec:
      containers:
        - name: integrated-praise-provider
          image: "{{ .Values.image.repository }}integrated-praise-provider"
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8015
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
